def print_body_part(num_guesses):
  if num_guesses == 5:
    print(" _______      ")
    print("|       |     ")
    print("|       |     ")
    print("|      _|_    ")
    print("|     /oo \   ")
    print("|     \O__/   ")
    print("|             ")
    print("|             ")
    print("|             ")
    print("|             ")
    print("|             ")
    print("              ")

  elif num_guesses == 4:
    print(" _______      ")
    print("|       |     ")
    print("}       |     ")
    print("|      _|_    ")
    print("|     / OO\   ")
    print("|     \__o/   ")
    print("|       |     ")
    print("|       |     ")
    print("|       |     ")
    print("|             ")
    print("|             ")
    print("              ")

  elif num_guesses == 3:
    print(" _______      ")
    print("|       |     ")
    print("|       |     ")
    print("|      _|_    ")
    print("|     /oo \   ")
    print("|     \o__/   ")
    print("|       |     ")
    print("|       |\    ")
    print("|       |     ")
    print("|             ")
    print("|             ")
    print("              ")

  elif num_guesses == 2:
    print(" _______      ")
    print("|       |     ")
    print("|       |     ")
    print("|      _|_    ")
    print("|     / oo\   ")
    print("|     \__0/   ")
    print("|       |     ")
    print("|      /|\    ")
    print("|       |     ")
    print("|             ")
    print("|             ")
    print("              ")

  elif num_guesses == 1:
    print(" _______        ")
    print("|       |       ")
    print("|       |       ")
    print("|      _|_      ")
    print("|     / oo\     ")
    print("|     \__O/ !!! ")
    print("|       |       ")
    print("|      /|\      ")
    print("|       |       ")
    print("|        \      ")
    print("|               ")
    print("                ")
  elif num_guesses == 0:
    print(" _______      ")
    print("|       |     ")
    print("|       |     ")
    print("|      _|_    ")
    print("|     / xx\   ")
    print("|     \__-/   ")
    print("|       |     ")
    print("|      /|\    ")
    print("|       |     ")
    print("|      / \    ")
    print("|             ")
    print("              ")
